{
 "title": "Demo K-8 Pod Metrics",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(machine_memory_bytes{},kubernetes_io_hostname)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container_name!=\"POD\"},namespace)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",container_name!=\"POD\"},pod_name)"
   },
   {
    "name": "container",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",container_name!=\"POD\",pod_name=\"$Pod\"},container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Container Image",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\",pod=\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Total Pods running for $namespace",
   "type": "gauge",
   "description": "These many Pods are running at any given time?",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "count (kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Container ( $container ) Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_status_running{pod_template_hash=\"\",namespace=\"$namespace\", pod=\"$Pod\",container=\"$container\"}"
    }
   ]
  },
  {
   "title": "Total Container ( $container ) restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod_template_hash=\"\",pod=\"$Pod\", container=\"$container\"} "
    }
   ]
  },
  { "title": "GO Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "go_goroutines $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "count go routines" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "$Pod"
    }
   ]
  },
  {
   "title": "go_memstats_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "alloc_bytes - $Pod"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "inuse_bytes - $Pod"
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Pod CPU usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"^$Pod$\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{ pod_name=\"$Pod\", container_name!=\"POD\"  }[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{kubernetes_io_hostname=\"$Node\"}[5m]))"
      }
     ]
    },
    {
     "title": "Pod memory working bytes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"})"
      }
     ]
    }
   ]
  },
  { "title": "Container Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Container ( $container ) Errors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",reason=\"Error\",pod=\"$Pod\",container=\"$container\",pod_template_hash=\"\"})"
    }
   ]
  },
  {
   "title": "Container ( $container ) OOM Kills",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",container=\"$container\",pod_template_hash=\"\",reason=\"OOMKilled\"})"
    }
   ]
  },
  {
   "title": "Container ( $container ) ContainerCannotRun",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",container=\"$container\",pod_template_hash=\"\",reason=\"ContainerCannotRun\"})"
    }
   ]
  },
  {
   "title": "Last Termination Reason for $container",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason!=\"\", namespace=\"$namespace\",container=\"$container\",pod_template_hash=\"\",pod=\"$Pod\"} > 0",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Pod ($Pod ) Waiting Reason",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{reason!=\"\", namespace=\"$namespace\",pod_template_hash=\"\",pod=\"$Pod\"} > 0",
     "legendFormat": " {{ container }}  {{ reason }}"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=\"$Pod\"}[5m])) by (pod_name)",
     "legendFormat": "{{ $Pod }}"
    }
   ]
  },
  { "title": "All processes CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "All processes CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",pod_name=~\"^$Pod$\"}[5m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=\"$Pod\",pod_template_hash=\"\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "All processes memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "All processes memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod_name=~\"^$Pod$\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Cpu usage (relative to limit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[120s])) by (namespace,container_name) / sum(container_spec_cpu_quota{container_name=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Memory usage (relative to limit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / sum(container_spec_memory_limit_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "actual"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Cpu usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[30s])) by (id,pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_name=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) / count(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (id,pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (container_name,namespace)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(kube_pod_container_resource_requests_memory_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container)",
     "legendFormat": "request"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Cpu usage (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[30s])) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_name=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) / count(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(kube_pod_container_resource_requests_memory_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container)",
     "legendFormat": "request"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Cpu usage (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"$container\", namespace=\"$namespace\"}[30s])) by (namespace,container_name)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_name=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{container_name=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_spec_memory_limit_bytes{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(kube_pod_container_resource_requests_memory_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container)",
     "legendFormat": "request"
    }
   ]
  },
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Network I/O pressure for $Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod_name=~\"^$Pod$\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod_name=~\"^$Pod$\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=\"$Pod\",pod_template_hash=\"\"}[5m])) by (pod_name)",
     "legendFormat": "receive -> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=\"$Pod\",pod_template_hash=\"\"}[5m])) by (pod_name)",
     "legendFormat": "transmit <- {{ pod_name }}"
    }
   ]
  },
  { "title": "All processes network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod_name=~\"^$Pod$\"}[5m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",pod_name=~\"^$Pod$\"}[5m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}